### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by jasonmac75** [Minh-Ton/Control-Center#1]
Hi i'm using macOS Mojave ver 10.14.2, in vmware pro I downloaded the Control.Center.dmg opened archive copied app to Applications.

When I click on app nothing happens, just doesn't launch?

**Comment by minh-ton** [comment]
Since it's a menubar app so it won't show the icon in the Dock after you open the app. You can check if your app has been opened by looking at your menubar, and find the Control Center icon.

**Comment by anstan1** [comment]
Hello, 

I am using macOS High Sierra 10.13.6, and I am experiencing a similar issue as OP. I have followed the instructions, and when I click on the Control Center.app file in Applications, nothing happens. I don't see the Control Center icon in the menubar.

Sometimes when I click on the Control Center.app, I get the following error : 

“Control Center” can’t be opened. You should move it to the Trash.

Thanks for your help!

**Comment by minh-ton** [comment]
> Hello,
> 
> I am using macOS High Sierra 10.13.6, and I am experiencing a similar issue as OP. I have followed the instructions, and when I click on the Control Center.app file in Applications, nothing happens. I don't see the Control Center icon in the menubar.
> 
> Sometimes when I click on the Control Center.app, I get the following error :
> 
> “Control Center” can’t be opened. You should move it to the Trash.
> 
> Thanks for your help!

I've updated the instruction on how to fix it in the README. Let me know if you still can't open the app.

Run the following command:

```sudo spctl --master-disable```
If you still cannot open the app, try with a different command:
```sudo xattr -d com.apple.quarantine /Applications/Control\ Center.app #Assuming the app is in the Applications folder```

**Comment by anstan1** [comment]
> 
> I've updated the instruction on how to fix it in the README. Let me know if you still can't open the app.
> 
> Run the following command:
> 
> `sudo spctl --master-disable`
> If you still cannot open the app, try with a different command:
> `sudo xattr -d com.apple.quarantine /Applications/Control\ Center.app #Assuming the app is in the Applications folder`

Thank you very much for your reply.

I tried both commands, but the application still does not open. I do  not see any icon in the menubar after trying to launch Control Center.app from Applications folder.

**Comment by minh-ton** [comment]
> > I've updated the instruction on how to fix it in the README. Let me know if you still can't open the app.
> > Run the following command:
> > `sudo spctl --master-disable`
> > If you still cannot open the app, try with a different command:
> > `sudo xattr -d com.apple.quarantine /Applications/Control\ Center.app #Assuming the app is in the Applications folder`
> 
> Thank you very much for your reply.
> 
> I tried both commands, but the application still does not open. I do not see any icon in the menubar after trying to launch Control Center.app from Applications folder.

Could you attach a screenshot/video? If you still cannot open the app, try right-clicking on the app => Show package contents => Contents => MacOS and run the binary file in it to see if the app would open or not. 

You can also try this command 
```sudo xcode-select --install && sudo codesign --force --deep --sign - /Applications/Control\ Center.app```

**Comment by jasonmac75** [comment]
when opening binary file - “Control Center” can’t be opened. You should move it to the Trash

**Comment by jasonmac75** [comment]
Last login: Tue Jul 14 09:06:21 on ttys001
192:~ username$ sudo xattr -d com.apple.quarantine /Applications/Control\ Center.app ; exit;
Password:
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jasonmac75** [comment]
Last login: Tue Jul 14 09:07:35 on ttys001
192:~ username$ sudo spctl --master-disable ; exit;
Password:
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jasonmac75** [comment]
Yeeesss this works, it prompted me to download xcode tools, just ignored and worked:
sudo xcode-select --install && sudo codesign --force --deep --sign - /Applications/Control\ Center.app

**Comment by minh-ton** [comment]
> Yeeesss this works, it prompted me to download xcode tools, just ignored and worked:
> 
> sudo xcode-select --install && sudo codesign --force --deep --sign - /Applications/Control\ Center.app

So you've able to run the app, right?

**Comment by anstan1** [comment]
@jasonmac75 I confirm that the codesign command worked as well for me. I already had the xcode tools. I can now see the icon in the menubar and it seems to be working.
 
Thanks for the tip!

Cheers!
