### ISSUE TITLE
There is no dmg in Control-Center-3

### ISSUE THREAD

**Issue by Wizkid305** [Minh-Ton/Control-Center#10]
Is the .zip supposed to automatically become the app or can you provide a link to a .dmg
The app also doesn't let me open the app and no icon shows in the top bar.

**Comment by Wizkid305** [comment]
![Screen Shot 2021-09-26 at 9 50 25 AM](https://user-images.githubusercontent.com/90802219/134810758-899e8f81-c327-4e16-8f81-403c098d81a8.png)
![Screen Shot 2021-09-26 at 9 50 04 AM](https://user-images.githubusercontent.com/90802219/134810761-e56f9e3a-9a80-4053-900b-73e0c5314406.png)

**Comment by Wizkid305** [comment]
I am using MacOS 10.15.7 Catalina on a mid-2012 MacBook Pr
![Screen Shot 2021-09-26 at 10 32 14 AM](https://user-images.githubusercontent.com/90802219/134812189-28564585-40bd-4c63-a8b9-586204a9d9a8.png)
o

**Comment by minh-ton** [comment]
Open `Terminal` app and run `sudo codesign --force --deep --sign - /Applications/Control\ Center.app`, then try to re-open the app.

**Comment by Wizkid305** [comment]
thank you very much
